### ISSUE TITLE
Help with topic

### ISSUE THREAD

**Issue by aldolereste** [bbidault/sphero_ros-project#1]
Hi

We have been playing with Sphero 2.0 as part of a school project and we would love to have more information about the following.

Edit: Oh sorry, I found the documentation!

Thanks
Aldolereste

**Comment by aldolereste** [comment]
Hi

After reading the documentation, I am back with some questions if I may

set_heading
If I got it right, this topic will make the ball roll around itself

I tried the following

rostopic pub set_heading std_msgs/Float32 90

To make the ball rotate with 90 degrees, but when I am moving it [0, 20, 0], it follows the same path it was following before publishing on set_heading topic.

Am I doing something wrong here?

I also wanted to know if and to what end, we can use the information from the published topics (Collision, diagnostics, imu, odom) 

Thank you
PS: can we disable the rotation the ball is making when it get to the destination point?

**Comment by bbidault** [comment]
Hi Aldolereste,

Sphero use a Cartesian coordinate system, but changing its heading with set_heading does not change its coordinate system. Thus, you should send an angular command to sphero as well as the linear command you are already sending (something more like [0, 20, 0], [90, 0, 0]) with cmd_vel.

You should also check this documentation : http://sdk.sphero.com/api-reference/api-quick-reference/

I am not sure to understand what you mean by "the rotation the ball is making", you should maybe try to work with cmd_vel or set_stabilization.

I hope I answered your questions,

Boris
